services:
  opensearch-node:
    image: opensearchproject/opensearch:latest
    container_name: local-opensearch
    environment:
      - cluster.name=local-cluster
      - node.name=opensearch-node
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
      - DISABLE_INSTALL_DEMO_CONFIG=true
      - DISABLE_SECURITY_PLUGIN=true # 로컬은 보안 없이 편하게!
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"
    networks:
      - local-net

  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:latest
    container_name: local-dashboards
    ports:
      - "5601:5601"
    environment:
      - 'OPENSEARCH_HOSTS=["http://opensearch-node:9200"]'
      - "DISABLE_SECURITY_DASHBOARDS_PLUGIN=true"
    networks:
      - local-net
    depends_on:
      - opensearch-node

networks:
  local-net:
    driver: bridge