spring.application.name=ssavice
springdoc.use-fqn=true
# [??] ?? ?? - ?? ?? ?? ?? ????? ?? ?? ?? ??
token.secret-key=testtesttesttesttesttesttesttest
token.access-validity-in-milliseconds=36000000000
token.refresh-validity-in-milliseconds=864000000
token.hash-secret-key=hashhashhashhashhashhashhashhash
# company signup email verification token 2?
company.signup.verify-token.secret-key=companytestcompanytestcompanytestcompanytest
company.signup.verify-token.validity-in-milliseconds=120000
# [??] S3 ??
s3.region=${S3_REGION}
s3.bucket=${S3_BUCKET_NAME}
s3.put-expiration-second=120
s3.get-expiration-min=10
# [??? ??? ??] 5MB
image.upload.max-bytes=5242880
#image.upload.max-bytes=5242
# SQS
spring.cloud.aws.region.static=${S3_REGION}
sqs.queue.thumbnail-alarm=${SQS_THUMB_ALARM_QUEUE}
spring.cloud.openfeign.client.config.default.connect-timeout=3000
spring.cloud.openfeign.client.config.default.read-timeout=5000
external.nts.url=https://api.odcloud.kr/api/nts-businessman/v1
external.nts.service-key=${NTS_SERVICE_KEY}
external.kakao.user-info-url=https://kapi.kakao.com/v2/user/me
external.toss.url=https://api.tosspayments.com/v1/payments
external.toss.secret-key=${TOSS_SECRET_KEY}

# Kafka
kafka.join-topic=join-topic

spring.kafka.bootstrap-servers=${KAFKA_SERVER_URL}
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
spring.kafka.producer.properties.spring.json.add.type.headers=true
spring.kafka.producer.acks=all
spring.kafka.producer.retries=3

spring.kafka.producer.properties.delivery.timeout.ms=120000
spring.kafka.producer.properties.request.timeout.ms=30000
spring.kafka.producer.properties.linger.ms=5
spring.kafka.producer.properties.batch.size=16384