spring.application.name=ssavice
springdoc.use-fqn=true
# [??] ?? ?? - ?? ?? ?? ?? ????? ?? ?? ?? ??
token.secret-key=testtesttesttesttesttesttesttest
token.access-validity-in-milliseconds=36000000000
token.refresh-validity-in-milliseconds=864000000
token.hash-secret-key=hashhashhashhashhashhashhashhash
# company signup email verification token 2?
company.signup.verify-token.secret-key=companytestcompanytestcompanytestcompanytest
company.signup.verify-token.validity-in-milliseconds=120000
# [??] S3 ??
s3.region=${S3_REGION}
s3.bucket=${S3_BUCKET_NAME}
s3.put-expiration-second=120
s3.get-expiration-min=10
# [??? ??? ??] 5MB
image.upload.max-bytes=5242880
#image.upload.max-bytes=5242
# SQS
spring.cloud.aws.region.static=${S3_REGION}
sqs.queue.thumbnail-alarm=${SQS_THUMB_ALARM_QUEUE}
spring.cloud.openfeign.client.config.default.connect-timeout=3000
spring.cloud.openfeign.client.config.default.read-timeout=5000
external.nts.url=https://api.odcloud.kr/api/nts-businessman/v1
external.nts.service-key=${NTS_SERVICE_KEY}
sqs.queue.outbox=${SQS_OUTBOX_QUEUE}

# OpenSearch
opensearch.host=${OPENSEARCH_HOST}
opensearch.port=443
opensearch.scheme=https
opensearch.password=${OPENSEARCH_PASSWORD}
opensearch.username=${OPENSEARCH_USERNAME}
