INSERT INTO address (gugun, gugun_code, region, region_code, latitude, longitude, geo_hash, post_code, address, detail_address, created_at, modified_at) VALUES ('북구', '27230', '산격동', '2723011100', 35.891926, 128.611010, 'wy7knt', '41566', '대구광역시 북구 대학로 80', '경북대학교 글로벌프라자', now(), now());
INSERT INTO address (gugun, gugun_code, region, region_code, latitude, longitude, geo_hash, post_code, address, detail_address, created_at, modified_at) VALUES ('북구', '27230', '산격동', '2723011100', 35.891926, 128.611010, 'wy7knt', '41566', '대구광역시 북구 대학로 80', '경북대학교 글로벌프라자', now(), now());
INSERT INTO address (gugun, gugun_code, region, region_code, latitude, longitude, geo_hash, post_code, address, detail_address, created_at, modified_at) VALUES ('북구', '27230', '산격동', '2723011100', 35.891926, 128.611010, 'wy7knt', '41566', '대구광역시 북구 대학로 80', '경북대학교 글로벌프라자', now(), now());
INSERT INTO account (provider, provider_id, role, created_at, modified_at) VALUES ('KAKAO', '1234567890', 'USER', now(), now());
INSERT INTO account (provider, provider_id, role, created_at, modified_at) VALUES ('KAKAO', '1234567890', 'COMPANY', now(), now());
INSERT INTO users (id, user_role, name, email, phone_number, image_resource_id, is_deleted, address_id, created_at, modified_at) VALUES (1, 'USER', '홍길동', 'default@email.com', '010-1234-5678', null, false, 2, now(), now());
INSERT INTO company (id, company_name, owner_name, phone_number, image_resource_id, business_number, description, depositor, account_number, is_deleted, address_id, created_at, modified_at, rate_count, rating_sum, business_name, start_date) VALUES (2, 'SSAVICE', '홍길동', '010-1234-5678', null, '0123456789', 'ssavice는 최저가 서비스를 위한 플랫폼입니다.', '홍길동', '01234567890', false, 1, now(), now(), 0, 0, '(주)SSAVICE', now());
INSERT INTO service_item (title, description, base_price, discount_rate, discounted_price, minimum_member, maximum_member, current_member, start_date, end_date, deadline, category, tag, is_deleted, thumbnail_image_resource_id, company_id, address_id, status, created_at, modified_at) VALUES ('여러 서비스를 최저가로 구매하세요', '저희 서비스는 공동구매를 통해 합리적인 가격을 제공합니다. 여러 사람이 함께할수록 더 낮아지는 가격으로, 최저가의 혜택을 경험해 보세요.', 10000, 10, 9000, 10, 20, 0, now() + INTERVAL 30 DAY, now() + INTERVAL 60 DAY, now() + INTERVAL 5 DAY, 'IT/인터넷', '', false, null, 2, 3, 'RECRUITING', now(), now());

